highlighter: rouge
gems:
  - jekyll-sitemap
ga: "UA-55584370-8"
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      last_modified_at: "2017-12-17"
